# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\normal_sliders.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NormalDialog(object):
    def setupUi(self, NormalDialog):
        NormalDialog.setObjectName("NormalDialog")
        NormalDialog.resize(1021, 796)
        self.buttonBox = QtWidgets.QDialogButtonBox(NormalDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 700, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(NormalDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 50, 971, 614))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 68, 139, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.hs_vhf = QtWidgets.QSlider(self.layoutWidget)
        self.hs_vhf.setOrientation(QtCore.Qt.Horizontal)
        self.hs_vhf.setObjectName("hs_vhf")
        self.verticalLayout_3.addWidget(self.hs_vhf)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.hs_hf = QtWidgets.QSlider(self.layoutWidget)
        self.hs_hf.setOrientation(QtCore.Qt.Horizontal)
        self.hs_hf.setObjectName("hs_hf")
        self.verticalLayout_3.addWidget(self.hs_hf)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.hs_mhf = QtWidgets.QSlider(self.layoutWidget)
        self.hs_mhf.setOrientation(QtCore.Qt.Horizontal)
        self.hs_mhf.setObjectName("hs_mhf")
        self.verticalLayout_3.addWidget(self.hs_mhf)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.hs_mf = QtWidgets.QSlider(self.layoutWidget)
        self.hs_mf.setOrientation(QtCore.Qt.Horizontal)
        self.hs_mf.setObjectName("hs_mf")
        self.verticalLayout_3.addWidget(self.hs_mf)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.hs_mlf = QtWidgets.QSlider(self.layoutWidget)
        self.hs_mlf.setOrientation(QtCore.Qt.Horizontal)
        self.hs_mlf.setObjectName("hs_mlf")
        self.verticalLayout_3.addWidget(self.hs_mlf)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.hs_lf = QtWidgets.QSlider(self.layoutWidget)
        self.hs_lf.setOrientation(QtCore.Qt.Horizontal)
        self.hs_lf.setObjectName("hs_lf")
        self.verticalLayout_3.addWidget(self.hs_lf)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.hs_vlf = QtWidgets.QSlider(self.layoutWidget)
        self.hs_vlf.setOrientation(QtCore.Qt.Horizontal)
        self.hs_vlf.setObjectName("hs_vlf")
        self.verticalLayout_3.addWidget(self.hs_vlf)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(810, 610))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(24, 55, 400, 521))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(NormalDialog)
        self.buttonBox.accepted.connect(NormalDialog.accept)
        self.buttonBox.rejected.connect(NormalDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NormalDialog)

    def retranslateUi(self, NormalDialog):
        _translate = QtCore.QCoreApplication.translate
        NormalDialog.setWindowTitle(_translate("NormalDialog", "Normal Adjustment"))
        self.groupBox.setTitle(_translate("NormalDialog", "Detail Level"))
        self.label_2.setText(_translate("NormalDialog", "Very High Frequency"))
        self.label_3.setText(_translate("NormalDialog", "High Frequency"))
        self.label_4.setText(_translate("NormalDialog", "Medium High Frequency"))
        self.label_5.setText(_translate("NormalDialog", "Medium Frequency"))
        self.label_6.setText(_translate("NormalDialog", "Medium Low Frequency"))
        self.label_7.setText(_translate("NormalDialog", "Low Frequency"))
        self.label_8.setText(_translate("NormalDialog", "Very Low Frequency"))
        self.groupBox_2.setTitle(_translate("NormalDialog", "Normal"))
        self.label.setText(_translate("NormalDialog", "TextLabel"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NormalDialog = QtWidgets.QDialog()
    ui = Ui_NormalDialog()
    ui.setupUi(NormalDialog)
    NormalDialog.show()
    sys.exit(app.exec_())
