# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_filter.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PluginGui(object):
    def setupUi(self, PluginGui):
        PluginGui.setObjectName("PluginGui")
        PluginGui.resize(213, 662)
        self.mainTabs = QtWidgets.QTabWidget(PluginGui)
        self.mainTabs.setGeometry(QtCore.QRect(0, 0, 211, 659))
        self.mainTabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.mainTabs.setObjectName("mainTabs")
        self.Bilateral_tab = QtWidgets.QWidget()
        self.Bilateral_tab.setObjectName("Bilateral_tab")
        self.layoutWidget = QtWidgets.QWidget(self.Bilateral_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 161, 631))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.labelDiameter = QtWidgets.QLabel(self.layoutWidget)
        self.labelDiameter.setMinimumSize(QtCore.QSize(80, 0))
        self.labelDiameter.setObjectName("labelDiameter")
        self.verticalLayout_41.addWidget(self.labelDiameter)
        self.bilateral_dia_spin = QtWidgets.QSpinBox(self.layoutWidget)
        self.bilateral_dia_spin.setMinimum(-1)
        self.bilateral_dia_spin.setMaximum(150)
        self.bilateral_dia_spin.setProperty("value", 5)
        self.bilateral_dia_spin.setObjectName("bilateral_dia_spin")
        self.verticalLayout_41.addWidget(self.bilateral_dia_spin)
        self.verticalLayout.addLayout(self.verticalLayout_41)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.labelSColor = QtWidgets.QLabel(self.layoutWidget)
        self.labelSColor.setMinimumSize(QtCore.QSize(80, 0))
        self.labelSColor.setObjectName("labelSColor")
        self.verticalLayout_40.addWidget(self.labelSColor)
        self.bilateral_sigma_color_spin = QtWidgets.QSpinBox(self.layoutWidget)
        self.bilateral_sigma_color_spin.setMaximum(160)
        self.bilateral_sigma_color_spin.setProperty("value", 50)
        self.bilateral_sigma_color_spin.setObjectName("bilateral_sigma_color_spin")
        self.verticalLayout_40.addWidget(self.bilateral_sigma_color_spin)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_40.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.verticalLayout_40)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.labelSSpace = QtWidgets.QLabel(self.layoutWidget)
        self.labelSSpace.setMinimumSize(QtCore.QSize(80, 0))
        self.labelSSpace.setObjectName("labelSSpace")
        self.verticalLayout_39.addWidget(self.labelSSpace)
        self.bilateral_sigma_space_spin = QtWidgets.QSpinBox(self.layoutWidget)
        self.bilateral_sigma_space_spin.setMaximum(160)
        self.bilateral_sigma_space_spin.setProperty("value", 50)
        self.bilateral_sigma_space_spin.setObjectName("bilateral_sigma_space_spin")
        self.verticalLayout_39.addWidget(self.bilateral_sigma_space_spin)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_39.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.verticalLayout_39)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.labelBorderType = QtWidgets.QLabel(self.layoutWidget)
        self.labelBorderType.setMinimumSize(QtCore.QSize(80, 0))
        self.labelBorderType.setObjectName("labelBorderType")
        self.verticalLayout_38.addWidget(self.labelBorderType)
        self.bilateral_border_type_combo = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bilateral_border_type_combo.sizePolicy().hasHeightForWidth())
        self.bilateral_border_type_combo.setSizePolicy(sizePolicy)
        self.bilateral_border_type_combo.setObjectName("bilateral_border_type_combo")
        self.verticalLayout_38.addWidget(self.bilateral_border_type_combo)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_38.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.verticalLayout_38)
        self.mainTabs.addTab(self.Bilateral_tab, "")
        self.blur_tab = QtWidgets.QWidget()
        self.blur_tab.setObjectName("blur_tab")
        self.layoutWidget1 = QtWidgets.QWidget(self.blur_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 6, 161, 631))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(101, 0))
        self.label.setObjectName("label")
        self.verticalLayout_37.addWidget(self.label)
        self.blur_kernel_spin = QtWidgets.QSpinBox(self.layoutWidget1)
        self.blur_kernel_spin.setMinimum(3)
        self.blur_kernel_spin.setMaximum(35)
        self.blur_kernel_spin.setSingleStep(2)
        self.blur_kernel_spin.setProperty("value", 5)
        self.blur_kernel_spin.setObjectName("blur_kernel_spin")
        self.verticalLayout_37.addWidget(self.blur_kernel_spin)
        self.verticalLayout_2.addLayout(self.verticalLayout_37)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(101, 0))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_36.addWidget(self.label_2)
        self.blur_anchor_x_spin = QtWidgets.QSpinBox(self.layoutWidget1)
        self.blur_anchor_x_spin.setMinimum(-1)
        self.blur_anchor_x_spin.setProperty("value", -1)
        self.blur_anchor_x_spin.setObjectName("blur_anchor_x_spin")
        self.verticalLayout_36.addWidget(self.blur_anchor_x_spin)
        self.verticalLayout_2.addLayout(self.verticalLayout_36)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(101, 0))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_35.addWidget(self.label_3)
        self.blur_anchor_y_spin = QtWidgets.QSpinBox(self.layoutWidget1)
        self.blur_anchor_y_spin.setMinimum(-1)
        self.blur_anchor_y_spin.setMaximum(1024)
        self.blur_anchor_y_spin.setProperty("value", -1)
        self.blur_anchor_y_spin.setObjectName("blur_anchor_y_spin")
        self.verticalLayout_35.addWidget(self.blur_anchor_y_spin)
        self.verticalLayout_2.addLayout(self.verticalLayout_35)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(101, 0))
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.blur_border_type_combo = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blur_border_type_combo.sizePolicy().hasHeightForWidth())
        self.blur_border_type_combo.setSizePolicy(sizePolicy)
        self.blur_border_type_combo.setObjectName("blur_border_type_combo")
        self.verticalLayout_3.addWidget(self.blur_border_type_combo)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.mainTabs.addTab(self.blur_tab, "")
        self.box_tab = QtWidgets.QWidget()
        self.box_tab.setObjectName("box_tab")
        self.layoutWidget2 = QtWidgets.QWidget(self.box_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 161, 621))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.box_normalize_check = QtWidgets.QCheckBox(self.layoutWidget2)
        self.box_normalize_check.setObjectName("box_normalize_check")
        self.verticalLayout_4.addWidget(self.box_normalize_check)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_33.addItem(spacerItem8)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_33.addWidget(self.label_5)
        self.box_kernel_spin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.box_kernel_spin.setMinimum(3)
        self.box_kernel_spin.setMaximum(35)
        self.box_kernel_spin.setSingleStep(2)
        self.box_kernel_spin.setProperty("value", 5)
        self.box_kernel_spin.setObjectName("box_kernel_spin")
        self.verticalLayout_33.addWidget(self.box_kernel_spin)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_33.addItem(spacerItem9)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_34.addWidget(self.label_9)
        self.box_depth_spin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.box_depth_spin.setMinimum(-1)
        self.box_depth_spin.setProperty("value", -1)
        self.box_depth_spin.setObjectName("box_depth_spin")
        self.verticalLayout_34.addWidget(self.box_depth_spin)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_34.addWidget(self.label_10)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_34.addItem(spacerItem10)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_34.addWidget(self.label_11)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_32.addWidget(self.label_6)
        self.box_anchor_x_spin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.box_anchor_x_spin.setMinimum(-1)
        self.box_anchor_x_spin.setMaximum(1024)
        self.box_anchor_x_spin.setProperty("value", -1)
        self.box_anchor_x_spin.setObjectName("box_anchor_x_spin")
        self.verticalLayout_32.addWidget(self.box_anchor_x_spin)
        self.verticalLayout_34.addLayout(self.verticalLayout_32)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_34.addItem(spacerItem11)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_30.addWidget(self.label_7)
        self.box_anchor_y_spin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.box_anchor_y_spin.setMinimum(-1)
        self.box_anchor_y_spin.setMaximum(1024)
        self.box_anchor_y_spin.setProperty("value", -1)
        self.box_anchor_y_spin.setObjectName("box_anchor_y_spin")
        self.verticalLayout_30.addWidget(self.box_anchor_y_spin)
        self.verticalLayout_34.addLayout(self.verticalLayout_30)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_34.addItem(spacerItem12)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_29.addWidget(self.label_8)
        self.box_border_type_combo = QtWidgets.QComboBox(self.layoutWidget2)
        self.box_border_type_combo.setObjectName("box_border_type_combo")
        self.verticalLayout_29.addWidget(self.box_border_type_combo)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_29.addItem(spacerItem13)
        self.verticalLayout_34.addLayout(self.verticalLayout_29)
        self.verticalLayout_33.addLayout(self.verticalLayout_34)
        self.verticalLayout_4.addLayout(self.verticalLayout_33)
        self.mainTabs.addTab(self.box_tab, "")
        self.gaussian_tab = QtWidgets.QWidget()
        self.gaussian_tab.setObjectName("gaussian_tab")
        self.layoutWidget3 = QtWidgets.QWidget(self.gaussian_tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 161, 631))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem14)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_28.addWidget(self.label_36)
        self.gaussian_kernel_spin = QtWidgets.QSpinBox(self.layoutWidget3)
        self.gaussian_kernel_spin.setMinimum(3)
        self.gaussian_kernel_spin.setMaximum(35)
        self.gaussian_kernel_spin.setSingleStep(2)
        self.gaussian_kernel_spin.setObjectName("gaussian_kernel_spin")
        self.verticalLayout_28.addWidget(self.gaussian_kernel_spin)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_28.addItem(spacerItem15)
        self.verticalLayout_26.addLayout(self.verticalLayout_28)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(81, 0))
        self.label_13.setObjectName("label_13")
        self.verticalLayout_26.addWidget(self.label_13)
        self.gaussian_sig_x_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.gaussian_sig_x_spin.setObjectName("gaussian_sig_x_spin")
        self.verticalLayout_26.addWidget(self.gaussian_sig_x_spin)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem16)
        self.verticalLayout_5.addLayout(self.verticalLayout_26)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(81, 0))
        self.label_14.setObjectName("label_14")
        self.verticalLayout_25.addWidget(self.label_14)
        self.gaussian_sig_y_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget3)
        self.gaussian_sig_y_spin.setObjectName("gaussian_sig_y_spin")
        self.verticalLayout_25.addWidget(self.gaussian_sig_y_spin)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem17)
        self.verticalLayout_5.addLayout(self.verticalLayout_25)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(81, 0))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_24.addWidget(self.label_15)
        self.gaussian_border_type_combo = QtWidgets.QComboBox(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gaussian_border_type_combo.sizePolicy().hasHeightForWidth())
        self.gaussian_border_type_combo.setSizePolicy(sizePolicy)
        self.gaussian_border_type_combo.setObjectName("gaussian_border_type_combo")
        self.verticalLayout_24.addWidget(self.gaussian_border_type_combo)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem18)
        self.verticalLayout_5.addLayout(self.verticalLayout_24)
        self.mainTabs.addTab(self.gaussian_tab, "")
        self.median_tab = QtWidgets.QWidget()
        self.median_tab.setObjectName("median_tab")
        self.layoutWidget4 = QtWidgets.QWidget(self.median_tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 160, 161, 72))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_23.addWidget(self.label_16)
        self.median_kernel_spin = QtWidgets.QSpinBox(self.layoutWidget4)
        self.median_kernel_spin.setMinimum(3)
        self.median_kernel_spin.setMaximum(35)
        self.median_kernel_spin.setSingleStep(2)
        self.median_kernel_spin.setProperty("value", 5)
        self.median_kernel_spin.setObjectName("median_kernel_spin")
        self.verticalLayout_23.addWidget(self.median_kernel_spin)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_23.addWidget(self.label_17)
        self.mainTabs.addTab(self.median_tab, "")
        self.filter2d_tab = QtWidgets.QWidget()
        self.filter2d_tab.setObjectName("filter2d_tab")
        self.layoutWidget5 = QtWidgets.QWidget(self.filter2d_tab)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 80, 151, 110))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_6.addWidget(self.label_33)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_6.addWidget(self.label_35)
        self.mainTabs.addTab(self.filter2d_tab, "")
        self.derivatives_tab = QtWidgets.QWidget()
        self.derivatives_tab.setObjectName("derivatives_tab")
        self.layoutWidget6 = QtWidgets.QWidget(self.derivatives_tab)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 10, 161, 621))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.derivatives_sobel_radio = QtWidgets.QRadioButton(self.layoutWidget6)
        self.derivatives_sobel_radio.setObjectName("derivatives_sobel_radio")
        self.verticalLayout_7.addWidget(self.derivatives_sobel_radio)
        self.derivatives_scharr_radio = QtWidgets.QRadioButton(self.layoutWidget6)
        self.derivatives_scharr_radio.setObjectName("derivatives_scharr_radio")
        self.verticalLayout_7.addWidget(self.derivatives_scharr_radio)
        self.derivatives_laplacian_radio = QtWidgets.QRadioButton(self.layoutWidget6)
        self.derivatives_laplacian_radio.setObjectName("derivatives_laplacian_radio")
        self.verticalLayout_7.addWidget(self.derivatives_laplacian_radio)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem19)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(75, 0))
        self.label_21.setObjectName("label_21")
        self.verticalLayout_21.addWidget(self.label_21)
        self.derivatives_ddepth_spin = QtWidgets.QSpinBox(self.layoutWidget6)
        self.derivatives_ddepth_spin.setObjectName("derivatives_ddepth_spin")
        self.verticalLayout_21.addWidget(self.derivatives_ddepth_spin)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem20)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.derivatives_dx_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget6)
        self.derivatives_dx_spin.setMinimum(0.1)
        self.derivatives_dx_spin.setObjectName("derivatives_dx_spin")
        self.horizontalLayout_19.addWidget(self.derivatives_dx_spin)
        self.verticalLayout_22.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_21.addWidget(self.label_27)
        self.derivatives_dy_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget6)
        self.derivatives_dy_spin.setMinimum(0.1)
        self.derivatives_dy_spin.setObjectName("derivatives_dy_spin")
        self.horizontalLayout_21.addWidget(self.derivatives_dy_spin)
        self.verticalLayout_22.addLayout(self.horizontalLayout_21)
        self.verticalLayout_21.addLayout(self.verticalLayout_22)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem21)
        self.verticalLayout_8.addLayout(self.verticalLayout_21)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(75, 0))
        self.label_22.setObjectName("label_22")
        self.verticalLayout_20.addWidget(self.label_22)
        self.derivatives_kernel_spin = QtWidgets.QSpinBox(self.layoutWidget6)
        self.derivatives_kernel_spin.setMinimum(-1)
        self.derivatives_kernel_spin.setMaximum(33)
        self.derivatives_kernel_spin.setSingleStep(2)
        self.derivatives_kernel_spin.setProperty("value", -1)
        self.derivatives_kernel_spin.setObjectName("derivatives_kernel_spin")
        self.verticalLayout_20.addWidget(self.derivatives_kernel_spin)
        self.verticalLayout_8.addLayout(self.verticalLayout_20)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem22)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(75, 0))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_19.addWidget(self.label_23)
        self.derivatives_scale_spin = QtWidgets.QDoubleSpinBox(self.layoutWidget6)
        self.derivatives_scale_spin.setMinimum(0.1)
        self.derivatives_scale_spin.setObjectName("derivatives_scale_spin")
        self.verticalLayout_19.addWidget(self.derivatives_scale_spin)
        self.verticalLayout_8.addLayout(self.verticalLayout_19)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem23)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(75, 0))
        self.label_24.setObjectName("label_24")
        self.verticalLayout_18.addWidget(self.label_24)
        self.derivatives_delta_spin = QtWidgets.QSpinBox(self.layoutWidget6)
        self.derivatives_delta_spin.setObjectName("derivatives_delta_spin")
        self.verticalLayout_18.addWidget(self.derivatives_delta_spin)
        self.verticalLayout_8.addLayout(self.verticalLayout_18)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem24)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(75, 0))
        self.label_25.setObjectName("label_25")
        self.verticalLayout_17.addWidget(self.label_25)
        self.derivatives_border_type_combo = QtWidgets.QComboBox(self.layoutWidget6)
        self.derivatives_border_type_combo.setObjectName("derivatives_border_type_combo")
        self.verticalLayout_17.addWidget(self.derivatives_border_type_combo)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem25)
        self.derivatives_normalize_check = QtWidgets.QCheckBox(self.layoutWidget6)
        self.derivatives_normalize_check.setObjectName("derivatives_normalize_check")
        self.verticalLayout_17.addWidget(self.derivatives_normalize_check)
        self.verticalLayout_8.addLayout(self.verticalLayout_17)
        self.mainTabs.addTab(self.derivatives_tab, "")
        self.morphology_tab = QtWidgets.QWidget()
        self.morphology_tab.setObjectName("morphology_tab")
        self.layoutWidget7 = QtWidgets.QWidget(self.morphology_tab)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 10, 161, 631))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.morph_erode_radio = QtWidgets.QRadioButton(self.layoutWidget7)
        self.morph_erode_radio.setObjectName("morph_erode_radio")
        self.verticalLayout_9.addWidget(self.morph_erode_radio)
        self.morph_dilate_radio = QtWidgets.QRadioButton(self.layoutWidget7)
        self.morph_dilate_radio.setObjectName("morph_dilate_radio")
        self.verticalLayout_9.addWidget(self.morph_dilate_radio)
        self.morph_morph_radio = QtWidgets.QRadioButton(self.layoutWidget7)
        self.morph_morph_radio.setObjectName("morph_morph_radio")
        self.verticalLayout_9.addWidget(self.morph_morph_radio)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem26)
        self.verticalLayout_16.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(81, 0))
        self.label_28.setObjectName("label_28")
        self.verticalLayout_10.addWidget(self.label_28)
        self.morph_shape_combo = QtWidgets.QComboBox(self.layoutWidget7)
        self.morph_shape_combo.setObjectName("morph_shape_combo")
        self.verticalLayout_10.addWidget(self.morph_shape_combo)
        self.morph_kernel_label = QtWidgets.QLabel(self.layoutWidget7)
        self.morph_kernel_label.setObjectName("morph_kernel_label")
        self.verticalLayout_10.addWidget(self.morph_kernel_label)
        self.morph_kernel_spin = QtWidgets.QSpinBox(self.layoutWidget7)
        self.morph_kernel_spin.setMinimum(3)
        self.morph_kernel_spin.setMaximum(35)
        self.morph_kernel_spin.setSingleStep(2)
        self.morph_kernel_spin.setProperty("value", 5)
        self.morph_kernel_spin.setObjectName("morph_kernel_spin")
        self.verticalLayout_10.addWidget(self.morph_kernel_spin)
        self.verticalLayout_16.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(81, 0))
        self.label_34.setObjectName("label_34")
        self.verticalLayout_11.addWidget(self.label_34)
        self.morph_iteration_spin = QtWidgets.QSpinBox(self.layoutWidget7)
        self.morph_iteration_spin.setMinimum(1)
        self.morph_iteration_spin.setMaximum(5)
        self.morph_iteration_spin.setObjectName("morph_iteration_spin")
        self.verticalLayout_11.addWidget(self.morph_iteration_spin)
        spacerItem27 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem27)
        self.verticalLayout_16.addLayout(self.verticalLayout_11)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(81, 0))
        self.label_29.setObjectName("label_29")
        self.verticalLayout_15.addWidget(self.label_29)
        self.morph_type_combo = QtWidgets.QComboBox(self.layoutWidget7)
        self.morph_type_combo.setObjectName("morph_type_combo")
        self.verticalLayout_15.addWidget(self.morph_type_combo)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem28)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(81, 0))
        self.label_30.setObjectName("label_30")
        self.verticalLayout_14.addWidget(self.label_30)
        self.morph_border_type_combo = QtWidgets.QComboBox(self.layoutWidget7)
        self.morph_border_type_combo.setObjectName("morph_border_type_combo")
        self.verticalLayout_14.addWidget(self.morph_border_type_combo)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem29)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_31.setMinimumSize(QtCore.QSize(81, 0))
        self.label_31.setObjectName("label_31")
        self.verticalLayout_13.addWidget(self.label_31)
        self.morph_color_patch = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.morph_color_patch.sizePolicy().hasHeightForWidth())
        self.morph_color_patch.setSizePolicy(sizePolicy)
        self.morph_color_patch.setMinimumSize(QtCore.QSize(0, 57))
        self.morph_color_patch.setFrameShape(QtWidgets.QFrame.Panel)
        self.morph_color_patch.setFrameShadow(QtWidgets.QFrame.Plain)
        self.morph_color_patch.setLineWidth(3)
        self.morph_color_patch.setObjectName("morph_color_patch")
        self.verticalLayout_13.addWidget(self.morph_color_patch)
        spacerItem30 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem30)
        self.verticalLayout_16.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMinimumSize(QtCore.QSize(81, 0))
        self.label_32.setObjectName("label_32")
        self.verticalLayout_12.addWidget(self.label_32)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.morph_anchor_x_spin = QtWidgets.QSpinBox(self.layoutWidget7)
        self.morph_anchor_x_spin.setMinimum(-1)
        self.morph_anchor_x_spin.setMaximum(1024)
        self.morph_anchor_x_spin.setProperty("value", -1)
        self.morph_anchor_x_spin.setObjectName("morph_anchor_x_spin")
        self.horizontalLayout_25.addWidget(self.morph_anchor_x_spin)
        self.morph_anchor_y_spin = QtWidgets.QSpinBox(self.layoutWidget7)
        self.morph_anchor_y_spin.setMinimum(-1)
        self.morph_anchor_y_spin.setMaximum(1024)
        self.morph_anchor_y_spin.setProperty("value", -1)
        self.morph_anchor_y_spin.setObjectName("morph_anchor_y_spin")
        self.horizontalLayout_25.addWidget(self.morph_anchor_y_spin)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.verticalLayout_16.addLayout(self.verticalLayout_12)
        spacerItem31 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem31)
        self.mainTabs.addTab(self.morphology_tab, "")
        self.layoutWidget8 = QtWidgets.QWidget(PluginGui)
        self.layoutWidget8.setGeometry(QtCore.QRect(20, -230, 83, 49))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(81, 0))
        self.label_12.setObjectName("label_12")
        self.verticalLayout_27.addWidget(self.label_12)
        self.layoutWidget9 = QtWidgets.QWidget(PluginGui)
        self.layoutWidget9.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")

        self.retranslateUi(PluginGui)
        self.mainTabs.setCurrentIndex(6)
        self.blur_border_type_combo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(PluginGui)

    def retranslateUi(self, PluginGui):
        _translate = QtCore.QCoreApplication.translate
        PluginGui.setWindowTitle(_translate("PluginGui", "Form"))
        self.Bilateral_tab.setAccessibleName(_translate("PluginGui", "BilateralFilter"))
        self.labelDiameter.setText(_translate("PluginGui", "Diameter:"))
        self.labelSColor.setText(_translate("PluginGui", "Sigma Color:"))
        self.labelSSpace.setText(_translate("PluginGui", "Sigma Space:"))
        self.labelBorderType.setText(_translate("PluginGui", "Border:"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.Bilateral_tab), _translate("PluginGui", "Bilateral"))
        self.label.setText(_translate("PluginGui", "Kernel Size:"))
        self.label_2.setText(_translate("PluginGui", "Anchor Point X:"))
        self.label_3.setText(_translate("PluginGui", "Anchor Point Y:"))
        self.label_4.setText(_translate("PluginGui", "Border Type:"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.blur_tab), _translate("PluginGui", "Blur"))
        self.box_normalize_check.setText(_translate("PluginGui", "Normalize"))
        self.label_5.setText(_translate("PluginGui", "Kernel Size:"))
        self.label_9.setText(_translate("PluginGui", "Depth:"))
        self.label_10.setText(_translate("PluginGui", "(-1 same as source)"))
        self.label_6.setText(_translate("PluginGui", "Anchor Point X:"))
        self.label_7.setText(_translate("PluginGui", "Anchor Point Y:"))
        self.label_8.setText(_translate("PluginGui", "Border Type:"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.box_tab), _translate("PluginGui", "Box"))
        self.label_36.setText(_translate("PluginGui", "Kernel"))
        self.label_13.setText(_translate("PluginGui", "Sigma X:"))
        self.label_14.setText(_translate("PluginGui", "Sigma Y:"))
        self.label_15.setText(_translate("PluginGui", "Border Type:"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.gaussian_tab), _translate("PluginGui", "Gaussian"))
        self.label_16.setText(_translate("PluginGui", "Kernel Size:"))
        self.label_17.setText(_translate("PluginGui", "uses BorderType replicate"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.median_tab), _translate("PluginGui", "Median"))
        self.label_18.setText(_translate("PluginGui", "Kernel Matrix is constant"))
        self.label_33.setText(_translate("PluginGui", " and set  in the code."))
        self.label_19.setText(_translate("PluginGui", "Change it to experiment "))
        self.label_20.setText(_translate("PluginGui", "with various different "))
        self.label_35.setText(_translate("PluginGui", "Kernel Matricies"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.filter2d_tab), _translate("PluginGui", "Filter2D"))
        self.derivatives_sobel_radio.setText(_translate("PluginGui", "Sobel"))
        self.derivatives_scharr_radio.setText(_translate("PluginGui", "Scharr"))
        self.derivatives_laplacian_radio.setText(_translate("PluginGui", "Laplacian"))
        self.label_21.setText(_translate("PluginGui", "Desired Depth:"))
        self.label_26.setText(_translate("PluginGui", "Dx:"))
        self.label_27.setText(_translate("PluginGui", "Dy:"))
        self.label_22.setText(_translate("PluginGui", "Kernel Size:"))
        self.label_23.setText(_translate("PluginGui", "Scale:"))
        self.label_24.setText(_translate("PluginGui", "Delta offset:"))
        self.label_25.setText(_translate("PluginGui", "Border Type:"))
        self.derivatives_normalize_check.setText(_translate("PluginGui", "Normalize"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.derivatives_tab), _translate("PluginGui", "Derivatives"))
        self.morph_erode_radio.setText(_translate("PluginGui", "Erode"))
        self.morph_dilate_radio.setText(_translate("PluginGui", "Dilate"))
        self.morph_morph_radio.setText(_translate("PluginGui", "Morph"))
        self.label_28.setText(_translate("PluginGui", "Morph Shape:"))
        self.morph_kernel_label.setText(_translate("PluginGui", "Kernel:"))
        self.label_34.setText(_translate("PluginGui", "Iterations:"))
        self.label_29.setText(_translate("PluginGui", "Morph Type:"))
        self.label_30.setText(_translate("PluginGui", "Border Type:"))
        self.label_31.setText(_translate("PluginGui", "Border Color:"))
        self.morph_color_patch.setText(_translate("PluginGui", "TextLabel"))
        self.label_32.setText(_translate("PluginGui", "Anchor Point:"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.morphology_tab), _translate("PluginGui", "Morphology"))
        self.label_12.setText(_translate("PluginGui", "Kernel Size:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PluginGui = QtWidgets.QWidget()
    ui = Ui_PluginGui()
    ui.setupUi(PluginGui)
    PluginGui.show()
    sys.exit(app.exec_())
